Edited the Readme.md file #1
cnoam/spark-course pull request #2
Opened 2023-11-02 12:38 UTC by StavC

* Reviewed the installation process in a clean state Win11, everything works just fine.
* Edited some steps in the Readme.md file for better clarity.

2023-11-05 11:30 UTC, cnoam requested changes
I think you forgot to add the assets dir. 
When adding, make sure the link names are relative (and not "stav/assets" )

2023-11-05 11:49 UTC, StavC commented
> I think you forgot to add the assets dir. When adding, make sure the link names are relative (and not "stav/assets" )

should be fine now

2023-11-06 17:08 UTC, StavC commented
Just added two mini exercises to the end of notebook 04 Spark SQL.

2023-11-08 07:53 UTC, cnoam commented on readme.md
> +## the 'run' command returns "docker: command not found:
the --> The

2023-11-08 08:01 UTC, cnoam commented
great work!

2023-11-08 08:24 UTC, merged